name: flutter_input_example
description: Example to show all input fields together with some form logic
# version: 1.3.0

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_input:
    path: ../

dev_dependencies:
  build_runner: ^1.9.0
  pedantic: ^1.9.0

flutter:
  uses-material-design: true