name: flutter_input_example
description: Example to show all input fields together with some form logic
version: 1.4.0

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_input:
    path: ../

dev_dependencies:
  build_runner: ^1.9.0
  pedantic: ^1.9.2

flutter:
  uses-material-design: true