name: flutter_input
description: Input fields with form for Flutter
homepage: https://github.com/djarjo/flutter_input
version: 0.2.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  pedantic: ^1.8.0

dev_dependencies:
  test: '>=1.9.4'
